function showError() {
    console.log( 'ha habido un s√∫per error');
  }
  
export {showError};